name: deploy delightable
on:
  push:
    branches:
      - main
    paths:
      - 'packages/application-tracker/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/application-tracker
    permissions:
      contents: read
    env:
      SECRET_APP_SIGNING_TOKEN: ${{ secrets.SECRET_APP_SIGNING_TOKEN }}
      AWS_ROLE_ARN: ${{secrets.AWS_DEPLOY_ROLE}}
      AWS_REGION: ap-southeast-2
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: corepack enable

      - run: npm ci --omit=dev

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsRoleSession

      - name: Verify role
        run: aws sts get-caller-identity


      - name: Deploy app
        run: npx sst deploy --stage production